apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "ivolve/simplest"
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ivolveacrproj123.azurecr.io/auth-service:b87d75f3e8cd6885d3f56e1e2494d0b26da88f0d
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: ivolve-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ivolve
spec:
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
