apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ivolveacrproj123.azurecr.io/frontend:fd6acc02f2d206e842274097ef164f4f1ff6572f
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ivolve-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ivolve
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
